CREATE TABLE PACIENTE(
    RUT VARCHAR2(15) PRIMARY KEY,
    NOMBRES VARCHAR2(250),
    APELLIDO_PATERNO VARCHAR2(80),
    APELLIDO_MATERNO VARCHAR2(80),
    EDAD NUMERIC(3),
    COMUNA VARCHAR2(80),
    CALLE VARCHAR2(80),
    NUMERO_CALLE NUMERIC(8)
);