--CREACION TABLES SPACE DATA + INDICE + TEMPORAL
CREATE TABLESPACE DT_EJERCICIO DATAFILE 'DBF_EJERCICIO.DBF' 
  SIZE 100M;
  
CREATE TABLESPACE DT_EJERCICIO_IDX DATAFILE 'DBF_EJERCICIO_IDX.DBF' 
  SIZE 100M;  
  
CREATE TEMPORARY TABLESPACE DT_EJERCICIO_TMP TEMPFILE 'DBF_EJERCICIO_TMP.DBF' 
  SIZE 100M;
  
-- CREACIÓN ROL
CREATE ROLE ADM_EJE;
-- ASIGNACIÓN DE PERMISOS AL ROL
GRANT CREATE SESSION TO ADM_EJE;
GRANT CREATE ANY TABLE TO ADM_EJE;
GRANT CREATE ROLE TO ADM_EJE;
GRANT CREATE USER TO ADM_EJE;
GRANT CREATE VIEW TO ADM_EJE;
GRANT CREATE ANY INDEX TO ADM_EJE;
GRANT CREATE TRIGGER TO ADM_EJE;
GRANT CREATE PROCEDURE TO ADM_EJE;
GRANT CREATE SEQUENCE TO ADM_EJE;

--CREACIÓN USUARIO
CREATE USER EJERCICIO IDENTIFIED BY "EJERCICIO" DEFAULT TABLESPACE 
DT_EJERCICIO TEMPORARY TABLESPACE DT_EJERCICIO_TMP ACCOUNT UNLOCK;

--PERMISOS SOBRES TABLESPACE ASOCIADOS AL USUARIO
GRANT UNLIMITED TABLESPACE TO EJERCICIO;

-- VOLCANDO PERMISOS DEL ROL ADM_EJE SOBRE CCARRENO
GRANT ADM_EJE TO EJERCICIO;
