CREATE TABLE PACIENTE(
    RUN VARCHAR2(15) PRIMARY KEY,
    NOMBRES VARCHAR2(250),
    APELLIDO_PATERNO VARCHAR2(80),
    APELLIDO_MATERNO VARCHAR2(80),
    TIPO_EMPLEADO VARCHAR2(50),    
    TELEFONO NUMERIC(11),
    TIPO_CONTRATO NUMERIC(1)
);