/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Empleado;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.EmpleadoDAO;

/**
 *
 * @author DieG0L / Seba
 */
public class FormularioListarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form FormularioListarEmpleado
     */
    public FormularioListarEmpleado() {
        initComponents();
        EmpleadoDAO dao = new EmpleadoDAO();
        List<Empleado> listadoEmpleado = dao.listar();
        
        tblEmpleado.setModel(new DefaultTableModel(
                new String[]{
                "RUN", "NOMBRES", 
                "APELLIDO_PATERNO", 
                "APELLIDO_MATERNO",
                "TIPO_EMPLEADO",
                "TELEFONO",
                "TIPO_CONTRATO"}, listadoEmpleado.size()
        ));
        
        for (int i = 0; i < listadoEmpleado.size(); i++) {
            tblEmpleado.setValueAt(listadoEmpleado.get(i).getRun(), i, 0);
            tblEmpleado.setValueAt(listadoEmpleado.get(i).getNombre(), i, 1);
            tblEmpleado.setValueAt(listadoEmpleado.get(i).getApellidoPaterno(), i, 2);
            tblEmpleado.setValueAt(listadoEmpleado.get(i).getApellidoMaterno(), i, 3);
            tblEmpleado.setValueAt(listadoEmpleado.get(i).getTipoEmpleado(), i, 4);
            tblEmpleado.setValueAt(listadoEmpleado.get(i).getTelefono(), i, 5);
            tblEmpleado.setValueAt(listadoEmpleado.get(i).getTipoContrato(), i, 6);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblRun = new javax.swing.JLabel();
        txtRun = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        scrListar = new javax.swing.JScrollPane();
        tblEmpleado = new javax.swing.JTable();

        setName("frame1"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(954, 496));

        jpanTitulo.setBackground(new java.awt.Color(51, 51, 0));
        jpanTitulo.setForeground(new java.awt.Color(153, 153, 0));
        jpanTitulo.setMinimumSize(new java.awt.Dimension(0, 0));
        jpanTitulo.setPreferredSize(new java.awt.Dimension(476, 40));

        jLabel1.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("LISTADO DE EMPLEADOS");
        jLabel1.setMaximumSize(new java.awt.Dimension(246, 28));
        jLabel1.setMinimumSize(new java.awt.Dimension(246, 28));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(246, 28));

        javax.swing.GroupLayout jpanTituloLayout = new javax.swing.GroupLayout(jpanTitulo);
        jpanTitulo.setLayout(jpanTituloLayout);
        jpanTituloLayout.setHorizontalGroup(
            jpanTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );
        jpanTituloLayout.setVerticalGroup(
            jpanTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblRun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRun.setText("RUN");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEmpleado.setPreferredSize(new java.awt.Dimension(0, 0));
        scrListar.setViewportView(tblEmpleado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblRun, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(scrListar, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar))
                    .addComponent(lblRun))
                .addGap(18, 18, 18)
                .addComponent(scrListar, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        EmpleadoDAO dao = new EmpleadoDAO();
        if("".equals(txtRun.getText())){
            List<Empleado> listadoEmpleado = dao.listar();
            tblEmpleado.setModel(new DefaultTableModel(
                new String[]{
                "RUN", "NOMBRES", 
                "APELLIDO_PATERNO", 
                "APELLIDO_MATERNO",
                "TIPO_EMPLEADO",
                "TELEFONO",
                "TIPO_CONTRATO"}, listadoEmpleado.size()
        ));
        
            for (int i = 0; i < listadoEmpleado.size(); i++) {
                tblEmpleado.setValueAt(listadoEmpleado.get(i).getRun(), i, 0);
                tblEmpleado.setValueAt(listadoEmpleado.get(i).getNombre(), i, 1);
                tblEmpleado.setValueAt(listadoEmpleado.get(i).getApellidoPaterno(), i, 2);
                tblEmpleado.setValueAt(listadoEmpleado.get(i).getApellidoMaterno(), i, 3);
                tblEmpleado.setValueAt(listadoEmpleado.get(i).getTipoEmpleado(), i, 4);
                tblEmpleado.setValueAt(listadoEmpleado.get(i).getTelefono(), i, 5);
                tblEmpleado.setValueAt(listadoEmpleado.get(i).getTipoContrato(), i, 6);
            }
        }else{
            Empleado empleado = dao.buscarPorRun(txtRun.getText());
            tblEmpleado.setModel(new DefaultTableModel(
                new String[]{
                "RUN", "NOMBRES", 
                "APELLIDO_PATERNO", 
                "APELLIDO_MATERNO",
                "TIPO_EMPLEADO",
                "TELEFONO",
                "TIPO_CONTRATO"}, 1
        ));
            if(empleado != null){
                tblEmpleado.setValueAt(empleado.getRun(), 0, 0);
                tblEmpleado.setValueAt(empleado.getNombre(), 0, 1);
                tblEmpleado.setValueAt(empleado.getApellidoPaterno(), 0, 2);
                tblEmpleado.setValueAt(empleado.getApellidoMaterno(), 0, 3);
                tblEmpleado.setValueAt(empleado.getTipoEmpleado(), 0, 4);
                tblEmpleado.setValueAt(empleado.getTelefono(), 0, 5);
                tblEmpleado.setValueAt(empleado.getTipoContrato(), 0, 6);
            }
            
                
            
        }
                                         
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioListarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioListarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioListarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioListarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioListarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpanTitulo;
    private javax.swing.JLabel lblRun;
    private javax.swing.JScrollPane scrListar;
    private javax.swing.JTable tblEmpleado;
    private javax.swing.JTextField txtRun;
    // End of variables declaration//GEN-END:variables
}
