
package view;

import controller.Empleado;
import javax.swing.JOptionPane;
import model.EmpleadoDAO;

/**
 *
 * @author Diego-Seba
 */
   
public class FormularioEmpleado extends javax.swing.JFrame {
    private Empleado empleado;
    /**
     * Creates new form FormularioEmpleado
     */
    public FormularioEmpleado() {
        initComponents();
        Empleado empleado = new Empleado();
        accionCrear();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblRun = new javax.swing.JLabel();
        txtRun = new javax.swing.JTextField();
        lblApellidoPat = new javax.swing.JLabel();
        txtApellidoPat = new javax.swing.JTextField();
        lblApellidoMat = new javax.swing.JLabel();
        txtApellidoMat = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        cmbAccion = new javax.swing.JComboBox<>();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jpanTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lblTipoEmpleado = new javax.swing.JLabel();
        cmbTipoEmpleado = new javax.swing.JComboBox<>();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblContrato = new javax.swing.JLabel();
        txtContrato = new javax.swing.JTextField();
        lblGlosarioContrato = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenedor Empleado");
        setBackground(new java.awt.Color(255, 204, 0));

        lblNombre.setText("NOMBRE");

        lblRun.setText("RUN");

        lblApellidoPat.setText("APELLIDO PAT.");

        lblApellidoMat.setText("APELLIDO MAT.");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cmbAccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CREAR EMPLEADO", "GESTIONAR EMPLEADO" }));
        cmbAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccionActionPerformed(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jpanTitulo.setBackground(new java.awt.Color(51, 51, 0));
        jpanTitulo.setForeground(new java.awt.Color(153, 153, 0));

        lblTitulo.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 204, 0));
        lblTitulo.setText("Mantenedor Empleado");

        javax.swing.GroupLayout jpanTituloLayout = new javax.swing.GroupLayout(jpanTitulo);
        jpanTitulo.setLayout(jpanTituloLayout);
        jpanTituloLayout.setHorizontalGroup(
            jpanTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(221, 221, 221))
        );
        jpanTituloLayout.setVerticalGroup(
            jpanTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img.png"))); // NOI18N
        lblImagen.setText("lblImage");

        lblTipoEmpleado.setText("TIPO DE EMPLEADO");

        cmbTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.- JEFE TI", "2.- PROGRAMADOR", "3.- CAJERA", "4.- SUPERVISOR " }));
        cmbTipoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoEmpleadoActionPerformed(evt);
            }
        });

        lblTelefono.setText("TELEFONO");

        lblContrato.setText("TIPO CONTRATO");

        lblGlosarioContrato.setText("1 = Plazo Fijo     ;     2 = Contrato Indefinido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTipoEmpleado)
                            .addComponent(lblTelefono)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblApellidoMat)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblApellidoPat)
                                    .addComponent(lblRun)))
                            .addComponent(lblContrato))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoPat, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(cmbTipoEmpleado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtApellidoMat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(txtContrato)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnEditar)
                        .addGap(30, 30, 30)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(lblGlosarioContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRun)
                            .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidoPat)
                            .addComponent(txtApellidoPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidoMat)
                            .addComponent(txtApellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoEmpleado)
                            .addComponent(cmbTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblImagen)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrato)
                    .addComponent(txtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lblGlosarioContrato)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Empleado empleado = new Empleado();
        empleado.setNombre(txtNombre.getText());
        empleado.setRun(txtRun.getText());
        empleado.setApellidoPaterno(txtApellidoPat.getText());
        empleado.setApellidoMaterno(txtApellidoMat.getText());
        empleado.setTipoEmpleado((String) cmbTipoEmpleado.getSelectedItem());
        empleado.setTelefono(Integer.parseInt(txtTelefono.getText()));
        empleado.setTipoContrato(Integer.parseInt(txtContrato.getText()));
        
        System.out.println(empleado);
        
        //DATA ACCESS OBJECT
        EmpleadoDAO dao = new EmpleadoDAO();
        boolean resultado = dao.insertar(empleado);
        JOptionPane.showMessageDialog(null, "Empleado guardado exitosamente");
        System.out.println("insertado--->" + resultado);
        limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    public void accionCrear(){
        //habilitar texts
        txtRun.setEnabled(true);
        txtNombre.setVisible(true);
        txtApellidoPat.setVisible(true);
        txtApellidoMat.setVisible(true);
        cmbTipoEmpleado.setVisible(true);
        txtTelefono.setVisible(true);
        //mostrar labels
        lblNombre.setVisible(true);
        lblApellidoPat.setVisible(true);
        lblApellidoMat.setVisible(true);
        lblTipoEmpleado.setVisible(true);
        lblTelefono.setVisible(true);
        lblContrato.setVisible(true);
        lblGlosarioContrato.setVisible(true);
        txtContrato.setVisible(true);
        lblImagen.setVisible(true);
        
        //esconder componentes
        btnBuscar.setVisible(false);
        btnEditar.setVisible(false);
        btnEliminar.setVisible(false);
        btnGuardar.setVisible(true);
    }
    
    public void accionEditar(){
         //habilitar texts
        txtRun.setEnabled(true);
        txtNombre.setVisible(false);
        txtApellidoPat.setVisible(false);
        txtApellidoMat.setVisible(false);
        cmbTipoEmpleado.setVisible(false);
        txtTelefono.setVisible(false);
        //mostrar labels
        lblNombre.setVisible(false);
        lblApellidoPat.setVisible(false);
        lblApellidoMat.setVisible(false);
        lblTipoEmpleado.setVisible(false);
        lblTelefono.setVisible(false);
        lblContrato.setVisible(false);
        lblGlosarioContrato.setVisible(false);
        txtContrato.setVisible(false);        
        lblImagen.setVisible(true);
        //esconder componentes
        btnBuscar.setVisible(true);
        btnEditar.setVisible(false);
        btnEliminar.setVisible(false);
        btnGuardar.setVisible(false);
    }
    
    public void accionBuscar(){
        txtRun.setEnabled(false);
        txtNombre.setVisible(true);
        txtApellidoPat.setVisible(true);
        txtApellidoMat.setVisible(true);
        cmbTipoEmpleado.setVisible(true);
        txtTelefono.setVisible(true);
        //mostrar labels
        lblNombre.setVisible(true);
        lblApellidoPat.setVisible(true);
        lblApellidoMat.setVisible(true);
        lblTipoEmpleado.setVisible(true);
        lblTelefono.setVisible(true);
        lblContrato.setVisible(true);
        lblGlosarioContrato.setVisible(true);
        txtContrato.setVisible(true);        
        lblImagen.setVisible(true);
        //esconder componentes
        btnBuscar.setVisible(true);
        btnEditar.setVisible(true);
        btnEliminar.setVisible(true);
        btnGuardar.setVisible(false);
    }
           
    private void cmbAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccionActionPerformed
        if("CREAR EMPLEADO".equals(cmbAccion.getSelectedItem())){
            accionCrear();
        }
        if("GESTIONAR EMPLEADO".equals(cmbAccion.getSelectedItem())){
            accionEditar();
        }
    }//GEN-LAST:event_cmbAccionActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Guardar la informacion del formulario en objeto paciente
        String run = txtRun.getText();
        //DAO
        EmpleadoDAO dao = new EmpleadoDAO();
        Empleado emp = dao.buscarPorRun(run);
        
        if(emp != null){
            //crear una nueva accion
            accionBuscar();
            txtNombre.setText(emp.getNombre());
            txtApellidoPat.setText(emp.getApellidoPaterno());
            txtApellidoMat.setText(emp.getApellidoMaterno());
            cmbTipoEmpleado.setSelectedItem(emp.getTipoEmpleado());
            txtTelefono.setText(String.valueOf(txtTelefono.getText()));
            txtContrato.setText(String.valueOf(txtContrato.getText()));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Empleado empleado = new Empleado();
        empleado.setRun(txtRun.getText());
        empleado.setNombre(txtNombre.getText());
        empleado.setApellidoPaterno(txtApellidoPat.getText());
        empleado.setApellidoMaterno(txtApellidoMat.getText());
        empleado.setTipoEmpleado((String) cmbTipoEmpleado.getSelectedItem());
        empleado.setTelefono(Integer.parseInt(txtTelefono.getText()));
        empleado.setTipoContrato(Integer.parseInt(txtContrato.getText()));
        
        EmpleadoDAO dao = new EmpleadoDAO();
        boolean resultado = dao.actualizar(empleado);
        System.out.println("actualizado--> " + resultado);
        if(resultado){
            JOptionPane.showMessageDialog(rootPane, "El empleado se modifico exitosamente");
            limpiar();
        }else{
            JOptionPane.showMessageDialog(rootPane, "El empleado no se logró modificar");
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void cmbTipoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoEmpleadoActionPerformed
     if (empleado == null) {
        return; // Evitar ejecución si empleado es null
    }

    // Obtén el valor seleccionado en el JComboBox
    String tipoSeleccionado = (String) cmbTipoEmpleado.getSelectedItem();
    
    // Asigna el valor seleccionado al atributo tipoEmpleado
    empleado.setTipoEmpleado(tipoSeleccionado);
    
    }//GEN-LAST:event_cmbTipoEmpleadoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    String run = txtRun.getText();
    EmpleadoDAO dao = new EmpleadoDAO();
    Empleado emp = dao.buscarPorRun(run);
    if (emp != null) {
        // Si existe, eliminar el empleado
        boolean resultado = dao.eliminar(run);

        if (resultado) {
            JOptionPane.showMessageDialog(rootPane, "El empleado ha sido eliminado exitosamente");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se pudo eliminar al empleado");
        }
    } else {
        // Si no se encuentra el empleado, mostrar un mensaje
        JOptionPane.showMessageDialog(rootPane, "No se encontró un empleado con el RUN proporcionado");
    }

    }//GEN-LAST:event_btnEliminarActionPerformed

    public void limpiar(){
        txtRun.setText("");
        txtNombre.setText("");
        txtApellidoPat.setText("");
        txtApellidoMat.setText("");
        cmbTipoEmpleado.setSelectedItem("");
        txtTelefono.setText("");
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbAccion;
    private javax.swing.JComboBox<String> cmbTipoEmpleado;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jpanTitulo;
    private javax.swing.JLabel lblApellidoMat;
    private javax.swing.JLabel lblApellidoPat;
    private javax.swing.JLabel lblContrato;
    private javax.swing.JLabel lblGlosarioContrato;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRun;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoEmpleado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellidoMat;
    private javax.swing.JTextField txtApellidoPat;
    private javax.swing.JTextField txtContrato;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRun;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
